services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    # depends_on:
      # - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DB_CONN_RETRIES=30
      - DB_CONN_DELAY=2
    volumes:
      - .:/app
    command: python app.py

volumes:
  pgdata:
